name: "Hello Actions"
description: "Greet someone"
author: jwheeler71@github.com

inputs:
  MY_NAME:
    description: "who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"